name: CICD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: /opt/maven/bin/mvn compile
      
  security_check:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: trivy installation
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
        trivy --version
    - name: trivy fs scan
      run: trivy fs --format table -o fs-scan-report.json .
        

