name: CICD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: /opt/maven/bin/mvn compile
      
  security_check:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: trivy installation
      run: |
        sudo dnf install -y wget git unzip && \
        sudo rpm --import https://aquasecurity.github.io/trivy-repo/rpm/public.key && \
        sudo curl -sLo /etc/yum.repos.d/trivy.repo https://aquasecurity.github.io/trivy-repo/rpm/releases/trivy.repo && \
        sudo dnf install -y trivy && \
        trivy --version
    - name: trivy fs scan
      run: trivy fs --format table -o fs-scan-report.json .
        

